Jenkinsfile
pom.xml
src/it/shading-with-java-10-sources/pom.xml
src/it/shading-with-java-11-sources/invoker.properties
src/it/shading-with-java-11-sources/pom.xml
src/it/shading-with-java-11-sources/src/main/java/org/apache/maven/plugins/shade/its/App.java
src/it/shading-with-java-11-sources/verify.groovy

Jdk11 support

---

src/site/site.xml

Fix spelling mistake
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
- [ X ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ X ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Update site.xml spelling issue

---

pom.xml
src/main/java/org/apache/maven/plugins/shade/resource/ServicesResourceTransformer.java
src/test/java/org/apache/maven/plugins/shade/resource/ServiceResourceTransformerTest.java

I write a unit test to fix this bug. The fix is in SimpleRelocator
To …

[MSHADE-291] - Fixes bug in ServicesResourceTransformer

---

src/main/java/org/apache/maven/plugins/shade/DefaultShader.java
src/test/java/org/apache/maven/plugins/shade/DefaultShaderTest.java

[MSHADE-306] log all duplicates to not silently swallow a duplicate and an implicit selection

---

pom.xml
src/it/reloc-and-mini/invoker.properties
src/it/reloc-and-mini/pom.xml
src/it/reloc-and-mini/src/main/java/org/apache/maven/plugins/shade/its/App.java
src/it/reloc-and-mini/verify.bsh
src/main/java/org/apache/maven/plugins/shade/filter/MinijarFilter.java

I was chasing a problem and thought relocation and minification have a problem when working together. I've created the integration test to prove they are OK. It was just a configuration mistake on my end. …

[MSHADE-327] improved integration test coverage for relocation and minification

---

CONTRIBUTING.md

- Fix outdated links to dev mailing list and GitHub PR help
for the change (usually before you start working on it).~~  **Trivial changes like typos do not 
pulling in other changes.**
commit message.~~
be performed on your pull request automatically.~~ …

Update CONTRIBUTING hyperlinks

---

pom.xml

deps: update JUnit to 4.13

---

src/main/java/org/apache/maven/plugins/shade/resource/ServicesResourceTransformer.java

@michael-o and  replace deprecated method

[MSHADE-361] specify UTF-8 encoding per Java spec

---

pom.xml

[MSHADE-369] update commons-lang

---

pom.xml

[MSHADE-370] update mockito

---

.github/workflows/maven.yml

Signed-off-by: Olivier Lamy <olamy@apache.org>
To make clear that you …

run gh action with more jdk

---

src/main/java/org/apache/maven/plugins/shade/DefaultShader.java

[MSHADE-405] - ShowOverlapping Uses http instead of https

---

pom.xml

[MSHADE-416] Fix Jenkins URL

---

src/main/java/org/apache/maven/plugins/shade/pom/MavenJDOMWriter.java

[MSHADE-422] Remove usage of deprecated Plugin#getGoals() method

---

src/main/java/org/apache/maven/plugins/shade/pom/MavenJDOMWriter.java

JIRA issue: [MSHADE-430](https://issues.apache.org/jira/browse/MSHADE-430)
Related to #143 / [MSHADE-422](https://issues.apache.org/jira/browse/MSHADE-422)

[MSHADE-430] Remove usage of deprecated ModelBase#getReports()

---

src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java

(doc) Fix iterated collection

---

pom.xml

Use proper Guice, same as Maven. Drop sisu plugin, is defined in parent.
---
https://issues.apache.org/jira/browse/MSHADE-447

[MSHADE-447] Do not use forked guice, use sisu from parent

---

pom.xml

Changes:
* maven-dependency-tree 3.2.1
* commons-io 2.13.0
* commons-collections4 4.4
---
https://issues.apache.org/jira/browse/MSHADE-446

[MSHADE-446] Update dependencies

---

src/site/xdoc/download.xml.vm

[MSHADE-458] Refresh download page

---

pom.xml

[MSHADE-457] Upgrade Parent to 40

---

pom.xml

[MSHARED-464] Maven 3.6.3 as minimum requirements

---

src/it/projects/MSHADE-462/all/pom.xml
src/it/projects/MSHADE-462/invoker.properties
src/it/projects/MSHADE-462/one/pom.xml
src/it/projects/MSHADE-462/one/src/main/java/org/apache/one/One.java
src/it/projects/MSHADE-462/pom.xml
src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java

[MSHADE-462] 3.5.1 not compatible with 3.4.1: The version cannot be empty

---

src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java

As Plexus will silently add it as explain it in issue.
---
https://issues.apache.org/jira/browse/MSHADE-428

[MSHADE-428] Prevent null value in array of transformers

---

src/site/site.xml

Update site descriptor, use site configuration from parent
