apache/maven-shade-plugin

src/main/java/org/apache/maven/plugins/shade/DefaultShader.java
Maven always shows “Discovered module-info.class. Shading will break its strong encapsulation.” warning, even then the user has explicitly filtered those files out. The same with “META-INF/INDEX.LIST” file. 
This pull request fixes this by applying file filters BEFORE these built-in warning checkers.
=> [MSHADE-303] Suppress module-info.class warning if the file if filtered

src/it/MSHADE-316/dependency/src/main/java/x/y/z/SomeDependencyOfExemptedClass.java, src/it/MSHADE-316/dependency/src/main/java/x/y/z/SomeExemptedClass.java, src/main/java/org/apache/maven/plugins/shade/filter/MinijarFilter.java
Fixes [MSHADE-318](https://issues.apache.org/jira/projects/MSHADE/issues/MSHADE-318) - Specifically included class's dependencies are missing.
Solution: Include transitive dependencies of specifically included classes.
=> [MSHADE-318] - Include transitive dependencies

pom.xml
=> upgrade to asm 7.2

src/it/projects/MSHADE-351/pom.xml, src/it/projects/MSHADE-351/verify.bsh, src/main/java/org/apache/maven/plugins/shade/resource/properties/MicroprofileConfigTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/properties/SortedProperties.java
=> [MSHADE-351] make constructors public

pom.xml, src/main/java/org/apache/maven/plugins/shade/DefaultShader.java, src/main/java/org/apache/maven/plugins/shade/resource/ServicesResourceTransformer.java, src/test/java/org/apache/maven/plugins/shade/resource/ServiceResourceTransformerTest.java
@michael-o  These are the easy and relatively safe changes to remove the dependency on Guava and stick to Apache classes. There's one more usage of Multimap in core code that's going to need more careful work before we can rip it out completely.
=> [MSHADE-359] update guava

src/main/java/org/apache/maven/plugins/shade/resource/ServicesResourceTransformer.java, src/test/java/org/apache/maven/plugins/shade/DefaultShaderTest.java, src/test/java/org/apache/maven/plugins/shade/mojo/ShadeMojoTest.java, src/test/java/org/apache/maven/plugins/shade/resource/ServiceResourceTransformerTest.java, src/test/java/org/apache/maven/plugins/shade/resource/rule/TransformerTesterRule.java
=> use try with resources to close streams and fix warnings

src/main/java/org/apache/maven/plugins/shade/resource/ApacheNoticeResourceTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/ServicesResourceTransformer.java
@hboutemy this is also a tad more careful about character encodings
=> [MSHADE-360] avoid PrintWriter

src/main/java/org/apache/maven/plugins/shade/DefaultShader.java, src/test/java/org/apache/maven/plugins/shade/DefaultShaderTest.java
When a transformer handles a resource then the resource being duplicated is ok since the transformer will merge it so no need to log it (in particular as a warning).
---
=> [MSHADE-364] drop duplicates handled by a transformer

pom.xml, src/it/projects/MSHADE-363_old-Transformer/pom.xml, src/it/projects/MSHADE-363_old-Transformer/src/main/resources/Message.properties, src/it/projects/MSHADE-363_old-plugin/pom.xml, src/it/projects/MSHADE-363_old-plugin/src/main/resources/Message.properties, src/main/java/org/apache/maven/plugins/shade/DefaultShader.java, src/main/java/org/apache/maven/plugins/shade/resource/AbstractCompatibilityTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/ApacheNoticeResourceTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/AppendingTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/ComponentsXmlResourceTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/DontIncludeResourceTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/GroovyResourceTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/IncludeResourceTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/ManifestResourceTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/PluginXmlResourceTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/ReproducibleResourceTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/ResourceBundleAppendingTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/ServicesResourceTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/XmlAppendingTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/properties/PropertiesTransformer.java, src/test/java/org/apache/maven/plugins/shade/custom/CustomReproducibleResourceTransformer.java, src/test/java/org/apache/maven/plugins/shade/resource/ReproducibleResourceTransformer.java, src/test/java/org/apache/maven/plugins/shade/resource/rule/TransformerTesterRule.java
https://issues.apache.org/jira/browse/MSHADE-363
=> MSHADE-363 add ReproducibleResourceTransformer to restore compatibility

README.md, pom.xml, src/it/projects/MSHADE-183/verify.bsh, src/it/projects/MSHADE-373/pom.xml, src/it/projects/MSHADE-373/verify.bsh, src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java, src/main/java/org/apache/maven/plugins/shade/resource/ManifestResourceTransformer.java, src/test/java/org/apache/maven/plugins/shade/mojo/ShadeMojoTest.java
Manifest transformers in the shade plugin are often used to add meta-data for OSGi use since the shade and OSGi plugins are not overly compatible. If the same transformer is applied to the source plugin's manifest, the resolution will fail due to a duplicate bundle id.
It is therefore necessary to being able to opt-out of the manifest transformer when shading a source file. An example of this problem is documented in https://github.com/raphw/byte-buddy/issues/894.
https://issues.apache.org/jira/browse/MSHADE-373
=> MSHADE-373: adds a property to skip manifest transformer application when transforming a source file.

src/main/java/org/apache/maven/plugins/shade/relocation/SimpleRelocator.java, src/test/java/org/apache/maven/plugins/shade/relocation/SimpleRelocatorTest.java
**1. Make source shading respect package/class name excludes**
Fixes MSHADE-252.
Until now, there was a naive global search + replace for mapping `<pattern>` to `<shadedPattern>`, even if the corresponding packages are to be ignored. This works for binary JARs, but was completely broken for source JARs.
See also my related [comment in MSHADE-252](https://issues.apache.org/jira/browse/MSHADE-252?focusedCommentId=17314377&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17314377).
With this fix, on the one hand string replacement in source files works for both "dotty" strings like `my.package.name.Foo` and "slashy" ones like `/my/package/name/resource.properties`. On the other hand, source files are now being parsed `<pattern>` match by match and for each match …
=> [MSHADE-252] - Make source shading respect package/class name excludes

src/it/projects/MSHADE-382_skip_execution/invoker.properties, src/it/projects/MSHADE-382_skip_execution/pom.xml, src/it/projects/MSHADE-382_skip_execution/verify.groovy, src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java
Added a skip field to ShadeMojo to skip the execution.
To make clear …
=> [MSHADE-382] - Add property to skip execution

src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java, src/main/java/org/apache/maven/plugins/shade/relocation/SimpleRelocator.java, src/test/java/org/apache/maven/plugins/shade/relocation/SimpleRelocatorTest.java
Improve search & replace heuristics without destroying previously correct replacements in my test project (AspectJ). This solution is still bound to fail in some situations, simply because it is just a heuristic approach and not a full Java parser correctly recognising package names in all possible situations in Java source code. As for matching within Java string constants, this is next to impossible to get 100% right.
But the source shading feature is not meant as a source code generator anyway, merely as a tool creating reasonably plausible source code when navigating to a relocated library class from an IDE, hopefully displaying source code which makes 95% sense - no more, no less.
Supersedes #100 and fixes a few bugs regression I found with the new approach.
---
To make clear that …
=> [MSHADE-396] Improve SourceContent Shading

src/main/java/org/apache/maven/plugins/shade/relocation/SimpleRelocator.java, src/test/java/org/apache/maven/plugins/shade/relocation/SimpleRelocatorTest.java
=> [MSHADE-412] avoid possible NPE since rawString was added in SimpleRelocator

src/main/java/org/apache/maven/plugins/shade/resource/ServicesResourceTransformer.java, src/test/java/org/apache/maven/plugins/shade/resource/ServiceResourceTransformerTest.java
Signed-off-by: tison <wander4096@gmail.com>
To make clear that you …
=> [MSHADE-425] Relocate services name before add to serviceEntries

src/main/java/org/apache/maven/plugins/shade/DefaultShader.java, src/test/java/org/apache/maven/plugins/shade/DefaultShaderTest.java
https://issues.apache.org/jira/browse/MSHADE-431
Use a caching output stream to avoid overwriting the file if not needed
=> [MSHADE-431] Use a caching output stream

src/main/java/org/apache/maven/plugins/shade/resource/ServicesResourceTransformer.java, src/test/java/org/apache/maven/plugins/shade/DefaultShaderTest.java, src/test/java/org/apache/maven/plugins/shade/resource/ServiceResourceTransformerTest.java
JIRA issue: https://issues.apache.org/jira/browse/MSHADE-432
Supersedes https://github.com/apache/maven-shade-plugin/pull/32
Related to https://github.com/micronaut-projects/micronaut-profiles/issues/102
=> [MSHADE-432] Avoid duplicate META-INF/services entries

src/main/java/org/apache/maven/plugins/shade/filter/MinijarFilter.java, src/test/java/org/apache/maven/plugins/shade/filter/MinijarFilterTest.java
Follow-up on #104 and #83.
JIRA: https://issues.apache.org/jira/browse/MSHADE-366
The fact that the build output directory has to be handled is legit because the minifier calls `project.getRuntimeClassPathElements()` which returns a list of the project output dir and all dependencies jars.  It has to be handled specifically.  Any other directory will print a warning as currently.
It could be considered to switch the call to `project.getRuntimeClassPathElements()` to another call but that seems out of scope for this bug fix PR.
=> [MSHADE-366] "Access denied" during 'minimizeJar'

src/main/java/org/apache/maven/plugins/shade/DefaultShader.java, src/test/java/org/apache/maven/plugins/shade/DefaultShaderTest.java
Supersedes #140
JIRA issue: https://issues.apache.org/jira/browse/MSHADE-417 
Added a unit test.
=> [MSHADE-417] Fix null bytes appended to small files

src/it/projects/MSHADE-413-parallel/invoker.properties, src/it/projects/MSHADE-413-parallel/p1/pom.xml, src/it/projects/MSHADE-413-parallel/p2/pom.xml, src/it/projects/MSHADE-413-parallel/pom.xml, src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java
JIRA issue: [MSHADE-413](https://issues.apache.org/jira/browse/MSHADE-413)
May be fixing [MNG-7096](https://issues.apache.org/jira/browse/MNG-7096), [MSHADE-148](https://issues.apache.org/jira/browse/MSHADE-148), [MSHADE-384](https://issues.apache.org/jira/browse/MSHADE-384)...
Maven objects (like `Dependency` or `Model`) returned by Maven must not
be modified. Doing so will result in endless loops or incorrect builds.
is to use …
=> [MSHADE-413] Fix endless loop caused by manipulating shared objects

src/main/java/org/apache/maven/plugins/shade/DefaultShader.java
=> Update overlapping resources warning

pom.xml, src/it/projects/MSHADE-340_shadedTestJarArtifactAttached/pom.xml, src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java, src/test/java/org/apache/maven/plugins/shade/mojo/ShadeMojoTest.java
Up the baseline as for the rest of ASF plugins.
Changes:
* drop MAT
* drop uses of archaic constructs
Also update IT for MSHADE-340 as it was not passing with maven-jar-plugin 3+ version (maven 3.8.x used maven-jar-plugin 2.4), as the IT was replacing the main JAR intentionally, or unintentionally.
---
https://issues.apache.org/jira/browse/MSHADE-438
=> [MSHADE-438] Update to Maven 3.2.5

src/it/projects/MSHADE-36-inject-dep-reduced-pom-in-final/src/main/java/com/example/Main.java, src/main/java/org/apache/maven/plugins/shade/resource/ApacheNoticeResourceTransformer.java, src/main/java/org/apache/maven/plugins/shade/resource/DontIncludeResourceTransformer.java
Continuation of https://issues.apache.org/jira/browse/MNG-6829
Review requested of @elharo
Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu
=> [MNG-6829] Replace StringUtils#isEmpty(String) and #isNotEmpty(String)

src/main/java/org/apache/maven/plugins/shade/filter/MinijarFilter.java
The `toString()` method is not needed in cases the underlying method handles the conversion. Also calling toString() on a String is redundant. Removing them simplifies the code.
This change is minimal …
=> refactor: refactor bad smell UnnecessaryToStringCall

src/it/projects/MSHADE-105/bundle/pom.xml, src/it/projects/MSHADE-105/shaded-jar/pom.xml, src/it/projects/MSHADE-36-inject-dep-reduced-pom-in-final/pom.xml, src/it/projects/MSHADE-36-inject-dep-reduced-pom-in-final/verify.bsh, src/it/projects/MSHADE-391_noRelocationKeepOriginalClasses/pom.xml, src/it/projects/mini-jar-respect-includes/pom.xml, src/it/projects/mini-jar-respect-includes/verify.bsh, src/it/projects/project-with-reactors-included/pom.xml, src/it/projects/shading-with-java-8-sources/pom.xml, src/it/projects/shading-with-release-sources/pom.xml, src/it/projects/users-shader-impl/pom.xml
This is cosmetic only (no plugin code or dependency change) only for ITs. As ITs contains POMs with old dependencies that do trigger security alerts (despite they are harmless). Get rid of them as they look bad.
=> Get rid of security alerts

src/it/projects/MSHADE-467_parallel-dependency-reduced-pom/invoker.properties, src/it/projects/MSHADE-467_parallel-dependency-reduced-pom/pom.xml, src/it/projects/MSHADE-467_parallel-dependency-reduced-pom/shadeMT1/pom.xml, src/it/projects/MSHADE-467_parallel-dependency-reduced-pom/shadeMT2/pom.xml, src/it/projects/MSHADE-467_parallel-dependency-reduced-pom/shadeMT3/pom.xml, src/it/projects/MSHADE-467_parallel-dependency-reduced-pom/shadeMT4/pom.xml, src/it/projects/MSHADE-467_parallel-dependency-reduced-pom/verify.groovy, src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java
Fixes https://issues.apache.org/jira/browse/MSHADE-467.
You review the fix. I converted the reproducer project into the integration test from the first commit. The second commit makes the previously failing test pass.
=> [MSHADE-467] Fix concurrency problem with dependency-reduced POM

pom.xml
https://issues.apache.org/jira/browse/MSHADE-468
notice the use of plugin versions ranges "from x to y" to avoid showing the whole plugin releases history while explaining the range of releases sharing the same prerequisites
=> [MSHADE-468] add system requirements history

src/main/java/org/apache/maven/plugins/shade/DefaultShader.java
like https://github.com/codehaus-plexus/plexus-archiver/commit/b9ea3bf0e4c25c0a5cf1bcbc76e691067003dc36
=> [MSHADE-471] deal with DST

.github/workflows/maven-verify.yml, pom.xml, src/main/java/org/apache/maven/plugins/shade/DefaultShader.java, src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java, src/main/java/org/apache/maven/plugins/shade/resource/properties/io/NoCloseOutputStream.java
Drop dependencies that are superfluous (one class used) or are deprecated:
* drop commons-collections4
* drop (to be deprecated) maven-dependency-tree
Slight updates and cleanup in dependencies.
---
https://issues.apache.org/jira/browse/MSHADE-473
https://issues.apache.org/jira/browse/MSHADE-474
https://issues.apache.org/jira/browse/MSHADE-475
https://issues.apache.org/jira/browse/MSHADE-476
https://issues.apache.org/jira/browse/MSHADE-477
=> Drop the cruft

src/it/projects/extrajar-missing-file/invoker.properties, src/it/projects/extrajar-missing-file/pom.xml, src/it/projects/extrajar/pom.xml, src/it/projects/extrajar/verify.bsh, src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java
Ability to add "extra JARs and Artifacts" and still enjoy the full benefits of relocation, resource transformation, etc.
---
https://issues.apache.org/jira/browse/MSHADE-478
=> [MSHADE-478] Extra JARs feature

src/site/apt/index.apt.vm
Java 8 is required everywhere by Maven these days
@michael-o
=> Remove old note

src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java
No need to call out Java 1.8 as a special dependency anymore
=> Assume Java 1.8

src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java
This removes multiple screens of log cruft from every build that uses the shade plugin.
=> [MSHADE-479] Make the mojo much less noisy

pom.xml
The current ASM 9.7 does not support JDK 24 and 25 bytecode.
```
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.6.0:shade (default) on project kyuubi-spark-sql-engine_2.12: Error creating shaded jar: Problem shading JAR /Users/chengpan/.m2/repository/net/bytebuddy/byte-buddy/1.17.6/byte-buddy-1.17.6.jar entry META-INF/versions/24/net/bytebuddy/jar/asmjdkbridge/JdkClassWriter$1.class: java.lang.IllegalArgumentException: Unsupported class file major version 68 -> [Help 1]
...
```
---
=> Bump ASM 9.8 to support JDK 25 bytecode
